nodeLinker: node-modules

enableGlobalCache: false

checksumBehavior: throw

enableImmutableInstalls: true

enableInlineBuilds: true

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0061
    level: discard

npmScopes:
  gnus:
    npmRegistryServer: "https://registry.npmjs.org"
  geniusventures:
    npmRegistryServer: "https://registry.npmjs.org"
